name: post

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - run: npm run prod
      - run: vendor/bin/jigsaw build production
      - run: ls